name: semantic-segmentation-gpu
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.5.2
    - jupyter
    - matplotlib
    - opencv3
    - h5py
    - eventlet
    - flask-socketio
    - scikit-learn
    - scikit-image
    - ffmpeg
    - pandas
    - pip:
        - numpy==1.16.4
        - imageio==2.5.0
        - pillow==6.0.0
        - moviepy
        - tensorflow-gpu==1.13.1
        - keras

